# Rodar com docker-compose up -d --build
# Se não funcionar, tenta dar um colima start e brew install docker-compose

version: '3.1'

services:

  redis:
    container_name: redis-cache
    image: redis:alpine
    command: redis-server --requirepass root
    ports:
      - '6379:6379'
    networks:
      - technet

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - './db/mongo:/etc/mongo'
    networks:
      - technet

networks:
  technet:
    driver: bridge